(require-package 'haskell-mode)
(require 'haskell)
(require 'haskell-mode)
(require 'haskell-interactive-mode)
(require 'haskell-flycheck)
(require 'hi2)
(add-hook 'haskell-mode-hook 'turn-on-hi2)
;; (add-hook 'haskell-mode-hook 'turn-on-haskell-indent)
(setq haskell-process-args-cabal-repl
            '("--ghc-option=-ferror-spans" "--with-ghc=ghci-ng"))
(setq haskell-stylish-on-save t)
(add-hook 'haskell-mode-hook 'interactive-haskell-mode)
(define-key interactive-haskell-mode-map (kbd "C-c C-t") 'haskell-mode-show-type-at)
(define-key interactive-haskell-mode-map (kbd "M-.") 'haskell-mode-goto-loc)
(provide 'init-haskell)
